---
#podAnnotations:
#  example: client-foo
#antiAffinity: "soft"
#nodeAffinity: {}
nodeSelector:
  usecase: monitoring

initImage:
  repository: "busybox"
  tag: "latest"
  pullPolicy: "Always"

image:
  repository: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  tag: "6.5.3"
  pullPolicy: "IfNotPresent"

cluster_name: "logs"

heapSize: "2048m"

resources:
  requests:
    cpu: "25m"
    memory: "2000Mi"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  name: data
  size: "200Gi"
  storageClass: "gp2"

