public_env_variables:
      AMQP_HOST: rabbitmq
      AMQP_PLUGIN_HOST: rabbitmq
      AMQP_PLUGIN_PORT: '15672'
      AMQP_PORT: 'xxxx'
      AMQP_USER: user
      AMQP_PASSWORD: xxxx  
      CIPHER_KEY: xxxx
      EXTERNAL_API_BASIC_AUTH_TOKEN: xxxx
      AWS_S3_STORAGE: True
      AWS_STORAGE_BUCKET_NAME: s3-tf-otus-project
      AWS_ACCESS_KEY_ID: xxxx
      AWS_SECRET_ACCESS_KEY: xxxx
      AWS_S3_REGION_NAME:  eu-west-1
      AWS_S3_STATIC_URL: https://s3-tf-otus-project.s3.amazonaws.com/
      AWS_S3_MEDIA_URL: https://s3-tf-otus-project.s3.amazonaws.com/
      DATABASE_HOST: otus-project-hubdb.cq31byha9rid.eu-west-1.rds.amazonaws.com
      DATABASE_NAME: hubdb
      DATABASE_PORT: '5432'
      DATABASE_USER: otus-project
      DATABASE_PASSWORD: xxxx
      LANGUAGE_CODE: ru
      LOG_DATABASE_HOST: otus-project-logdb.cq31byha9rid.eu-west-1.rds.amazonaws.com
      LOG_DATABASE_NAME: logdb
      LOG_DATABASE_PORT: '5432'
      LOG_DATABASE_USER: otus-project
      LOG_DATABASE_PASSWORD: xxxx
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      TRANSPORT_TYPE: rmq
      WEBADMIN_EMAIL: root@otus-project.solutions
      WEBADMIN_PHONE: 000-00-00
      WEBADMIN_PASSWORD: qwerty
      DNS: otus-project.otus-project.solutions
      EMAIL_HOST: smtp.gmail.com
      EMAIL_HOST_USER: alert@otus-project.net
      EMAIL_PORT: '587'
      TIME_ZONE: Europe/Moscow
env_secret_name: "otus-project"
