  ---
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: {{ include "otus-project.name" . }}
    helm.sh/chart: {{ include "otus-project.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    env: {{ .Release.Namespace }}
  name: {{ include "otus-project.fullname" . }}-configs
kind: Secret
type: Opaque
data:
{{ (.Files.Glob "files/*").AsSecrets | indent 2 }}

